### ISSUE TITLE
Automated server setup

### ISSUE THREAD

**Issue by Reevak05** [Reevak05/StudentCommunityBot#20]
The bot sets up a server in the Student Community Model style (channels, roles, permissions). The user of this command shall give the bot (somehow) a list of classes in a format readable by the bot. The bot then creates general channels, grade channels, class channels, etc. and sets the appropriate permissions for each channel. The bot also creates the roles, including class roles, Admin, Mod, Supporter, grades, etc.

**Comment by MetalTurtle18** [comment]
# Automated Server Setup
## Channels (create channels and configure permissions
* General channel
* Info
* New members
* Server, Community announcements
* Bot commands
* 9th, 10th, 11th, 12th channels
* Voice channels
* Class categories and channels
* Admin, Mod channels

## Roles (create the roles)
* Admin role
* Mod role
* Supporter role
* 9th, 10th, 11th, 12th grade roles
* Class roles

**Comment by Reevak05** [comment]
## order:

1. create hardcoded roles (including grade roles)
2. create hardcoded categories
3. create hardcoded channels (including grade channels)
4. create class roles
5. create class categories
6. create class channels

**Comment by Reevak05** [comment]
## Plan of action

# `automated-server-setup-dev`: (@Reevak05 if not specified)
[add last few features (including setup category creation)
add storage of all channels and categories in channels.yml
clean up code and change to functions for readability
fix code to wait for prerequisite actions (@Camshaft54 and @Reevak05)
add confirmation button (@Camshaft54 and @Reevak05)](this_is_blue_for_emphasis)

`email-dev`: (@Camshaft54 if not specified)
add last few features (change to embeds, add thinking reaction, improve email HTML, change setup channel name to username)
edit wording of messaging (@Camshaft54 and @Reevak05)
change setup category ID to channels.yml (maybe merge both `automated-server-setup-dev` and `email-dev` into `main` first, then change this in a new PR)

`schedule-selection-dev`: (@MetalTurtle18 I think)
create schedule section process (the schedule selection should take place in the same channel as the email verification after the email is verified, so maybe wait until `email-dev` is merged into `main` before creating `schedule-selection-dev`
this should wait until the user is done with the setup process, then give them all of their roles

`member-information-storage-architecture-dev`:
create architecture to store information about members
change email verification code to be stored in the member information instead of in RAM so the verification process is unaffected in the case of a bot restart)

`required-roles-dev`:
set up required roles for commands properly so they use the Admin, Mod, and Supporter IDs from roles.yaml

*after these are done, continue from [Plan](https://github.com/Reevak05/StudentCommunityBot/projects/1)*
